[package]
name = "wasm-debug-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "binding"
path = "src/main.rs"

[dependencies]

[profile.release]
debug = true
